# Python basics

In [3]:
# python lists
l = [] # lege lijst
l = [1, 2, 3, 4, 5]
l = [x*x for x in l] # list comprehension

# dit gaat concateneren en niet optellen
# l + 2
l.append(2)
# dit gaat een lijst toevoegen en niet elk element afzonderlijk
#l.append([10,20,30])
l.extend([10,20,30])

print(l)

# slicing
print(l[1])
print(l[-3])      # begin vanachter te tellen als -1
print(l[3:-3])    # van tot
print(l[1:-1:2])  # start - stop - stapgrootte

[1, 4, 9, 16, 25, 2, 10, 20, 30]
4
10
[16, 25, 2]
[4, 16, 2, 20]


In [4]:
if l is not None: # None is de term voor null in python of onbestaand
    print("l is not none ;)")

if not (x and l):
    pass  # pass is om te zeggen dat de body hier stopt van functies/if/...

l is not none ;)


NameError: name 'x' is not defined

In [4]:
#for x in l:
for x in range(0,5):
    print(x)

while False:
    print("doet niets")

for index in range(len(l)): # len is de lengte opvragen
    value = l[index]

for index, value in enumerate(l):
    print(f"Element {index} heeft value {value}")

0
1
2
3
4
Element 0 heeft value 1
Element 1 heeft value 4
Element 2 heeft value 9
Element 3 heeft value 16
Element 4 heeft value 25
Element 5 heeft value 2
Element 6 heeft value 10
Element 7 heeft value 20
Element 8 heeft value 30


In [5]:
# hello world voorbeeld
print("Hello world!")
# voer cell uit met shift + enter
# a voor een extra cell erboven, b voor een cell eronder, met x doe je de geselecteerde cell weg (deselcteer de cell eerst met escape)
# als er problemen zijn met jupyter notebook -> installeer de extensie.

x = 10
x = 'Data Science'
x = True

# def = definieer een functie
# functienaam 
# parameterlijst
def optellen(a,b):
    return a + b

# met =5 zeg ik: dit is de defaultwaarde
def optellen2(a,b=5):
    return a + b

print(optellen(2, 8))
print(optellen2(2))


class Persoon:

    populatie = 0

    def __init__(self, naam, leeftijd):
        self.naam = naam
        self.leeftijd = leeftijd
        Persoon.populatie += 1 # ++ werkt niet in python

    def beschrijving(self):
        return f"{self.naam} is {self.leeftijd} jaar oud"
    
    @staticmethod
    def aantalPersonen():
        return Persoon.populatie
    
p1 = Persoon("Andy Weir", 28)
p2 = Persoon("Isaac Asimov", 80)

print(p1.beschrijving())
print(Persoon.aantalPersonen())

Hello world!
10
7
Andy Weir is 28 jaar oud
2


# Numpy basics

De basisstructuur in NumPy is de **ndarray** (n-dimensionale array). Een ndarray kan worden gezien als een rooster van elementen, allemaal van hetzelfde type, geïndexeerd door een tuple van niet-negatieve gehele getallen. Je kunt NumPy gebruiken om arrays te maken door gebruik te maken van de functie np.array(). Dit is een voorbeeld:

In [9]:
#import numpy
import numpy as np
#from numpy import random # importeer enkel de random functie uit numpy library/package

In [10]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In dit voorbeeld wordt een NumPy-array a gemaakt met de elementen 1 tot 5. Deze array is één-dimensionaal, maar NumPy ondersteunt ook meerdimensionale arrays. Een tweedimensionale array kan bijvoorbeeld als volgt worden gemaakt

In [11]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

Hier zie je een 2x3 matrix, wat betekent dat er twee rijen en drie kolommen zijn. Je kunt de vorm van een array opvragen met de shape-eigenschap:

In [ ]:
b.shape
# (2,3) = 2 rijen en 3 kolommen

NumPy biedt ook verschillende manieren om arrays te genereren zonder expliciet de waarden te specificeren. Bijvoorbeeld, np.zeros((2, 3)) maakt een 2x3 matrix gevuld met nullen, terwijl np.ones((2, 3)) een matrix met enen genereert. Je kunt ook een reeks getallen genereren met np.arange(), dat vergelijkbaar is met de ingebouwde range()-functie van Python, maar een NumPy-array retourneert.

Een van de belangrijkste voordelen van NumPy is de mogelijkheid om elementgewijze operaties uit te voeren op arrays. Dit betekent dat je dezelfde bewerking tegelijkertijd kunt toepassen op alle elementen van een array zonder een expliciete lus te schrijven. Bijvoorbeeld:

In [12]:
a + 2

array([3, 4, 5, 6, 7])

In dit voorbeeld wordt elk element van array c vermenigvuldigd met 2, wat resulteert in een nieuwe array d met de waarden [2, 4, 6, 8, 10]. Dergelijke operaties zijn niet alleen korter om te schrijven, maar ook sneller dan een vergelijkbare operatie met een Python-lijst.

In [ ]:
# alle codes heb ik meerdere keren uitgeprobeerd op verschillende manieren en numpy werd ge installed met een pip install